### PR TITLE
Low/High Stock Filtering

### PR DESCRIPTION
**Pull request by ZeroCoolHacker**
### Stock Availability
Now you can filter products with Higher than required or lower than required stock.

### CODE REVIEW

**Comment by Epse** [comment]
You are on a roll! Thank you very much this is amazing!

**Comment by ZeroCoolHacker** [comment]
What do you plan about this project?
Never thought about upgrading the front end to some framework like react or angular etc?

**Comment by Epse** [comment]
Honestly I don't know jack shit about "modern" front end. I am still a supporter of the low-tech solutions like the AJAX used here, since these work even on rather old browsers.

The reason I like support for old browsers and slow devices in EpPos is because a lot of the devices servers (as in the people in a cafe or restaurant) use are rather old and slow, but sturdy.

On the other hand, a nice modern UI could be really good for installations on new devices and use on tablets. Still, it would have to be fast.

It would be entirely possible to expand the backend API to be able to build a fully decoupled front-end. I have been thinking about expanding the API. I think for now that would mostly be adding an api call to get all products and to get an order. Then, if anyone would want to build a full-on heavy-duty front-end that would be possible and if it's fast enough I might add it.

**Comment by ZeroCoolHacker** [comment]
I have provided POS solutions to different organizations but they were java or C++ based as i was interested in those languages first. But now i want to work in python.
Have you looked in to django-rest-framework for api?

**Comment by Epse** [comment]
django-rest-framework looks interesting, but I think I'd prefer to just build it out myself. The current api's also don't use any framework and Django is perfectly able to do REST on it's own :)

**Comment by Epse** [comment]
Looks like we'll need to pull in django-rest-framework just for the auth...

**Pull request merged**
